In [1]:
import numpy as np
import pandas as pd
import datetime

In [2]:
species = ["Acer", "Aesculus", "Alnus", "Amaranthaceae", "Apiaceae", "Artemisia", "Asteraceae", "Betula", "Brassicaceae", "Cannabis", "Castanea", "Casuarina", "Cedrus", "Corylus", "Cupressaceae", "Cyperaceae", "Echium", "Ericaceae", "Fabaceae", "Fraxinus", "Helianthus", "Juncaceae", "Liguliflora", "Ligustrum", "Mercurialis", "Morus", "Myrtaceae", "Olea", "Oleaeceae", "Palmae", "Pinus", "Plantago", "Platanus", "Poaceae", "Populus", "Quercus", "Rosaceae", "Rumex", "Salix", "Sambucus", "Ulmus", "Urticaceae", "Urtica memb", "Indetermin"]

In [3]:
hours = np.array([datetime.datetime(2020, 1, 1) + datetime.timedelta(hours=i) for i in range(8760)])

In [4]:
database_dict = {"datetime": hours}
for s in species:
    database_dict[s] = np.random.randint(5000, size=8760)

In [5]:
polen_dataframe = pd.DataFrame(database_dict).set_index("datetime")
polen_dataframe

,Acer,Aesculus,Alnus,Amaranthaceae,Apiaceae,Artemisia,Asteraceae,Betula,Brassicaceae,Cannabis,...,Populus,Quercus,Rosaceae,Rumex,Salix,Sambucus,Ulmus,Urticaceae,Urtica memb,Indetermin
datetime,,,,,,,,,,,,,,,,,,,,,
2020-01-01 00:00:00,1887,2770,2265,2224,2298,1043,949,4723,3543,2172,...,289,1866,597,4797,240,559,4338,825,2622,2995
2020-01-01 01:00:00,1953,1906,4895,2650,3248,167,2252,1391,3650,2596,...,2475,319,4531,1211,646,995,3424,805,3360,4106
2020-01-01 02:00:00,2116,1301,4777,2832,771,4433,4468,2680,4780,3979,...,4310,1694,3813,1295,2476,3453,184,670,2222,1856
2020-01-01 03:00:00,4294,3612,695,3968,998,4528,2780,4540,4797,711,...,2281,4845,171,3071,4616,2047,1650,1957,4195,4985
2020-01-01 04:00:00,3346,4567,1495,3086,965,4773,564,1190,887,520,...,3386,2577,4137,4722,1347,1042,3757,3278,220,3529
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-30 19:00:00,1675,4126,3301,585,4152,513,2145,2878,790,4446,...,593,413,984,4647,1197,3937,1429,4714,4981,1646
2020-12-30 20:00:00,1956,3849,544,4053,2090,3356,3103,17,1173,1046,...,3861,3518,4241,1709,3016,3383,2999,2118,3964,2373
2020-12-30 21:00:00,4483,6,4388,562,871,4516,354,2205,130,1643,...,2147,3385,1192,567,898,1463,4926,3603,4096,3512
2020-12-30 22:00:00,3128,858,836,4473,2308,2627,976,4000,4185,4574,...,1604,2117,4150,880,4600,729,2910,830,4484,1695
2020-12-30 23:00:00,4790,30,469,2199,185,4071,4772,3018,3080,1922,...,2323,521,2833,4987,4310,1671,1355,1417,2452,4662

In [6]:
polen_dataframe.to_csv("polen_data.csv")

In [7]:
days = np.array([datetime.datetime(2020, 1, 1) + datetime.timedelta(days=i) for i in range(365)])

In [8]:
meteorological_columns = ["Tmean mean daily average temperature (ºC).",
"Tmax maximum daily average temperature (ºC).",
"Tmin minimum daily average temperature (ºC).",
"R total daily rainfall (mm).",
"RH daily average relative humidity (%).",
"WS daily average wind speed (km/h).",
"Wind NE daily average frequency of north-easterly winds (%).",
"Wind SE daily average frequency of south-easterly winds (%).",
"Wind SW daily average frequency of south-westerly winds (%).",
"Wind NW daily average frequency of north-westerly winds (%).",
"CF daily average frequency of calms (%).",
"Sunshine daily average sunshine (hours)."]

In [9]:
t_max = np.random.random(365)*25 + 10
t_min = t_max - np.random.random(365)*10

In [10]:
rainfall = np.random.random(365)*60

In [11]:
humidity = np.random.random(365)*100

In [12]:
windspeed = np.random.random(365)*100

In [13]:
wind = np.random.random((365, 4))
wind = (wind / wind.sum(axis=1)[:,None]) * 100

In [14]:
wind_NE = wind[:, 0]
wind_SE = wind[:, 1]
wind_SW = wind[:, 2]
wind_NW = wind[:, 3]

In [15]:
cf = np.random.random(365)*100

In [16]:
sunshine = np.random.random(365)*6+6

In [17]:
t_mean = (t_max + t_min) / 2

In [18]:
meteorological = {"datetime":days, "Tmean":t_mean, "Tmax":t_max, "Tmin":t_min, "Rainfall":rainfall, "Humidity":humidity, "WindSpeed":windspeed, "NE":wind_NE, "SE":wind_SE, "SW":wind_SW, "NW":wind_NW, "CalmFrequency":cf, "Sunshine":sunshine}

In [19]:
meteorological_dataframe = pd.DataFrame(meteorological).set_index("datetime")

In [20]:
meteorological_dataframe

,Tmean,Tmax,Tmin,Rainfall,Humidity,WindSpeed,NE,SE,SW,NW,CalmFrequency,Sunshine
datetime,,,,,,,,,,,,
2020-01-01,22.184428,25.959390,18.409465,36.782203,86.767036,9.038399,35.779183,24.837624,17.127318,22.255876,47.487091,9.747988
2020-01-02,17.762746,21.818733,13.706759,19.732245,24.914258,62.730918,14.774923,21.627696,20.036925,43.560456,44.982840,7.540710
2020-01-03,9.746973,10.492705,9.001241,27.610519,95.729976,65.476301,15.149443,6.780661,30.464784,47.605112,41.744646,7.969248
2020-01-04,8.253249,12.854730,3.651768,2.465660,10.579695,50.773263,19.200612,18.778171,32.454123,29.567094,87.203123,11.520919
2020-01-05,22.603882,25.918115,19.289650,35.100047,61.539792,76.097897,22.382994,28.397861,31.624781,17.594364,11.471185,11.641672
...,...,...,...,...,...,...,...,...,...,...,...,...
2020-12-26,16.761575,19.167256,14.355894,32.024272,16.904893,13.748118,18.208399,22.182800,23.025532,36.583269,60.537095,10.151014
2020-12-27,11.985101,12.135671,11.834532,17.137808,15.677365,17.152275,15.712135,4.830845,40.393100,39.063920,37.378541,10.159275
2020-12-28,21.668359,23.121411,20.215307,35.422564,30.108492,98.180199,29.453924,28.689738,21.172645,20.683693,39.436788,11.509785
2020-12-29,19.464571,21.548983,17.380158,16.049808,59.882224,20.656378,23.206631,7.844192,26.855434,42.093742,64.382294,6.165608
2020-12-30,9.925130,10.030735,9.819526,11.735377,21.999302,66.559528,33.283742,13.588741,24.727173,28.400343,44.943598,9.812825

In [21]:
meteorological_dataframe.to_csv("meteorological_data.csv")